export { default as InicioAdmin } from "../Admin/Inicio"
export { default as NoticiasAdmin } from "./Noticias"
export { default as EventosAdmin } from "../Admin/Eventos"
export { default as FinanzasAdmin } from "../Admin/Finanzas"
export { default as RegistrosAdmin } from "../Admin/Registros"
export { default as SociosAdmin } from "../Admin/Socios"
